/**
 * TypeScript mirror of the lighting-engine FastAPI schema
 * (shared/openapi.yaml, generated by `uv run python scripts/export_openapi.py`).
 *
 * Hand-maintained — keep in sync with components/schemas in the YAML. The
 * shape is small enough that a hand-typed mirror is easier to read and review
 * than `openapi-typescript`'s generated tree.
 */

// ---------- enums ----------

export type RoomType =
  | "living"
  | "dining"
  | "bedroom"
  | "kitchen"
  | "bathroom"
  | "study"
  | "hallway"
  | "staircase"
  | "foyer"
  | "outdoor"
  | "unknown";

export type RoomTier = "first_class" | "generic";

export type CeilingType = "none" | "flat" | "sloped" | "mixed";

export type Direction = "N" | "S" | "E" | "W";

export type Occupant = "kids" | "young_adult" | "adult" | "elderly";

export type FinishTone = "light" | "mid" | "dark";

export type Mood = "cozy" | "productive" | "wind_down" | "entertain";

export type TimeOfDay = "morning" | "evening" | "late_night";

export type JobStatusValue = "pending" | "running" | "done" | "failed";

export type DoorSwing = "in" | "out" | "sliding" | "unknown";

// ---------- geometry ----------

export interface Point {
  x: number;
  y: number;
}

export interface Door {
  id: string;
  wall_index?: number | null;
  along_wall?: number | null;
  width_m: number;
  height_m?: number;
  swing?: DoorSwing;
  /** Id of the room on the other side of the wall (parser inference).
   * `null`/undefined for exterior doors. */
  destination_room_id?: string | null;
}

export interface Window {
  id: string;
  wall_index?: number | null;
  along_wall?: number | null;
  width_m: number;
  height_m: number;
  sill_height_m: number;
  is_glazed_door?: boolean;
}

export interface Furniture {
  id: string;
  raw_label?: string | null;
  type?: string;
  position: Point;
  footprint?: Point[];
}

export interface CeilingFeature {
  id: string;
  kind: string;
  polygon: Point[];
  depth_m?: number;
}

export interface RoomDims {
  length_m: number;
  width_m: number;
}

// ---------- room / project ----------

export interface RoomSummary {
  id: string;
  name: string;
  type: RoomType;
  dims: RoomDims;
  ceiling_height_m?: number | null;
  polygon: Point[];
  doors: Door[];
  windows: Window[];
  confidence?: number;
  tier: RoomTier;
  status?: string;
}

export interface ProjectCreateResponse {
  project_id: string;
  rooms: RoomSummary[];
}

export interface RoomListResponse {
  rooms: RoomSummary[];
}

export interface WallConfirmation {
  index: number;
  confirm?: boolean;
  doors_confirmed?: Door[];
  windows_confirmed?: Window[];
  notes?: string;
}

export interface WallsResponse {
  project_id: string;
  room_id: string;
  walls: WallConfirmation[];
}

export interface ClarificationRequest {
  type_confirmed?: RoomType | null;
  length_m?: number | null;
  width_m?: number | null;
  ceiling_height_m?: number | null;
  ceiling_type?: CeilingType | null;
  main_window_orientation?: Direction | null;
  occupants?: Occupant[] | null;
  floor_finish?: FinishTone | null;
  wall_finish?: FinishTone | null;
}

export interface FurnitureRequest {
  furniture_notes?: string;
  mood?: Mood | null;
  activities?: string[];
}

export interface BriefRequest {
  intent_mood?: Mood | null;
  activities?: string[];
  time_of_use?: TimeOfDay[];
  notes?: string;
}

export interface ConfirmedRoom {
  id: string;
  name: string;
  type_inferred: RoomType;
  polygon_inferred: Point[];
  doors_parsed?: Door[];
  windows_parsed?: Window[];
  furniture_parsed?: Furniture[];
  ceiling_features_parsed?: CeilingFeature[];
  tier?: RoomTier;
  type_confirmed?: RoomType | null;
  length_m?: number | null;
  width_m?: number | null;
  ceiling_height_m?: number | null;
  ceiling_type?: CeilingType | null;
  main_window_orientation?: Direction | null;
  occupants?: Occupant[];
  floor_finish?: FinishTone | null;
  wall_finish?: FinishTone | null;
  walls?: WallConfirmation[];
  furniture_notes?: string;
  intent_mood?: Mood | null;
  activities?: string[];
  time_of_use?: TimeOfDay[];
  provenance?: Record<string, string>;
}

// ---------- generation ----------

export interface GenerateResponse {
  job_id: string;
}

export interface JobStatus {
  job_id: string;
  project_id: string;
  room_id: string;
  status: JobStatusValue;
  error?: string | null;
  result_url?: string | null;
  created_at: string;
  updated_at: string;
}

export interface LuxStats {
  mean_lux: number;
  min_lux: number;
  max_lux: number;
  uniformity: number;
  target_lux: number;
  meets_target: boolean;
}

export interface FixtureRow {
  sku: string;
  name: string;
  wattage_w: number;
  lumens: number;
  cct_k: number;
  cri: number;
  beam_angle_deg: number;
  count: number;
}

export interface PlanResponse {
  project_id: string;
  room_id: string;
  rcp_svg: string;
  furniture_svg: string;
  lux_uniformity: LuxStats;
  fixture_schedule: FixtureRow[];
  design_rationale: string;
  design_notes: string[];
  warnings: string[];
  metadata?: Record<string, unknown>;
}

// ---------- error envelope ----------

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: Record<string, unknown>;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}
