"""Canonical geometric IR for a parsed residential plan.

Units throughout this module are SI (meters) and degrees. Coordinates are in a
plan-local frame whose origin is the bottom-left of the detected plan region.
"""
from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field, computed_field, field_validator


class Point(BaseModel):
    model_config = ConfigDict(frozen=True)
    x: float
    y: float


class RoomType(StrEnum):
    living = "living"
    dining = "dining"
    bedroom = "bedroom"
    kitchen = "kitchen"
    bathroom = "bathroom"
    study = "study"
    hallway = "hallway"
    staircase = "staircase"
    foyer = "foyer"
    outdoor = "outdoor"
    unknown = "unknown"


class RoomTier(StrEnum):
    """Whether the room reaches the v1 design flow.

    - `first_class`: gets the full design pipeline (basics → walls → furniture
      → brief → RCP + furniture plan + lux uniformity). Habitable rooms where
      the designer's expertise actually moves the needle.
    - `generic`: shown in the room picker with a `tier: generic` flag.
      Generation pipeline for these is DEFERRED to v1.1 — v1 only generates
      for first-class rooms.
    - `hidden`: filtered out before the picker — toilets, storage, shafts,
      terraces, courtyards, staircases, balconies. Architects don't pay for
      lighting design on these in residential.

    Source: spec §3.1.
    """

    first_class = "first_class"
    generic = "generic"
    hidden = "hidden"


class DoorSwing(StrEnum):
    in_ = "in"
    out = "out"
    sliding = "sliding"
    unknown = "unknown"


class Window(BaseModel):
    # wall_index/along_wall are None when the parser hasn't snapped the opening to
    # a specific wall yet (v1 ships without wall-snapping — the designer can edit).
    id: str
    wall_index: int | None = None
    along_wall: float | None = Field(default=None, ge=0.0, le=1.0)
    width_m: float = Field(gt=0)
    height_m: float = Field(gt=0)
    sill_height_m: float = Field(ge=0)
    is_glazed_door: bool = False   # balcony-doors classified as windows for daylight


class Door(BaseModel):
    id: str
    wall_index: int | None = None
    along_wall: float | None = Field(default=None, ge=0.0, le=1.0)
    width_m: float = Field(gt=0)
    height_m: float = Field(gt=0, default=2.1)
    swing: DoorSwing = DoorSwing.unknown
    # ID of the room on the OTHER side of the wall this door sits on, when the
    # parser can infer it (door-destination inference, see
    # `parser/door_destinations.py`). `None` for exterior doors (balcony /
    # entrance) where there's no adjacent room polygon to anchor to.
    destination_room_id: str | None = None


class Furniture(BaseModel):
    id: str
    raw_label: str | None = None   # "FRIDGE", "sofa 053", block name, etc.
    type: str = "unknown"          # designer batch-tags this later
    position: Point
    footprint: list[Point] = []  # may be empty


class FixtureSource(StrEnum):
    """Where a Fixture entry came from."""
    parsed = "parsed"        # detected in the original DWG (architect's existing fixtures)
    proposed = "proposed"    # generated by the deterministic placement engine
    designer = "designer"    # added/moved by the designer in the UI (Chunk 3)


class LightingLayer(StrEnum):
    """Layered-lighting role of a fixture (residential design conventions)."""
    ambient = "ambient"
    task = "task"
    accent = "accent"
    decorative = "decorative"


class Fixture(BaseModel):
    id: str
    raw_label: str | None = None
    type: str = "unknown"          # designer batch-tags this (downlight, sconce, pendant, ...)
    position: Point
    mount_height_m: float | None = None  # None = ceiling-mounted
    source: FixtureSource = FixtureSource.parsed
    layer: LightingLayer = LightingLayer.ambient
    reasoning: str = ""            # human/LLM-readable rationale ("ambient grid fill")
    wattage_w: float | None = None
    lumens: float | None = None
    cct_k: int | None = None
    cri: int | None = None
    beam_angle_deg: float | None = None


class CeilingFeature(BaseModel):
    id: str
    kind: str                       # "beam" | "soffit" | "cove" | "height_change" | "skylight"
    polygon: list[Point]
    depth_m: float = 0.0

    @field_validator("polygon")
    @classmethod
    def _polygon_has_three_points(cls, v: list[Point]) -> list[Point]:
        if len(v) < 3:
            raise ValueError("polygon needs at least 3 points")
        return v


class Room(BaseModel):
    id: str
    name: str
    type: RoomType = RoomType.unknown
    # v1 picker filter — `hidden` by default so any new room type without an
    # explicit classification doesn't accidentally hit the design flow.
    # Populated by `parser/room_tier.classify_room_tier` in the pipeline.
    tier: RoomTier = Field(default=RoomTier.hidden)
    floor_level: int = 0           # 0 = ground/only floor; positive = upper floors
    polygon: list[Point]
    ceiling_height_m: float = Field(gt=0)
    windows: list[Window] = []
    doors: list[Door] = []
    furniture: list[Furniture] = []
    ceiling_features: list[CeilingFeature] = []
    existing_fixtures: list[Fixture] = []
    # Dotted/dashed-line regions inside the room that indicate "open to below"
    # (double-height / void). Each entry is a closed polygon in the local-meter
    # frame. Empty for v0 unless the parser's double-height detector finds one.
    double_height_polygons: list[list[Point]] = Field(default_factory=list[list[Point]])

    @field_validator("polygon")
    @classmethod
    def _polygon_has_three_points(cls, v: list[Point]) -> list[Point]:
        if len(v) < 3:
            raise ValueError("polygon needs at least 3 points")
        return v

    @computed_field  # type: ignore[prop-decorator]
    @property
    def area_sqm(self) -> float:
        # Shoelace formula
        n = len(self.polygon)
        s = 0.0
        for i in range(n):
            x1, y1 = self.polygon[i].x, self.polygon[i].y
            x2, y2 = self.polygon[(i + 1) % n].x, self.polygon[(i + 1) % n].y
            s += x1 * y2 - x2 * y1
        return abs(s) / 2.0


class Project(BaseModel):
    id: str
    name: str
    location: str = "delhi"
    floor_level: int = 0
    north_orientation_deg: float = 0.0
    rooms: list[Room] = []
